### ISSUE TITLE
"CVXOPT package needed to enforce constraints"

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-MAPMRI#1]
I've fixed some obvious issues with this app, but now I am seeing following app.

```
Traceback (most recent call last):
  File "/N/dc2/scratch/brlife/karst-workflows/59d4f89d6ac3590024d33731/59d4f89d6ac3590024d33734/main.py", line 44, in <module>
    positivity_constraint=True)
  File "/N/u/brlife/Karst/.local/lib/python2.7/site-packages/dipy/reconst/mapmri.py", line 235, in __init__
    'CVXOPT package needed to enforce constraints')
ValueError: CVXOPT package needed to enforce constraints
```

Who could help me with this issue?

**Comment by francopestilli** [comment]
Eleftherios would be best. @brain-life/dev

**Comment by soichih** [comment]
@garyfallidis Can you take a look?

**Comment by aarya22** [comment]
Maybe I'm stating the obvious, but you could try to install CVXOPT package on brain-life.

pip install cvxopt

**Comment by soichih** [comment]
@aarya22 That fixed it.

It generated following png.

![mapmri_maps_regularization](https://user-images.githubusercontent.com/923896/31246240-b39bfe44-a9da-11e7-81ce-8871275a7cfe.png)

How does it look?

By the way, the submit.pbs is looks for a wrong output file and task is still failing - even though it generates the final image
> https://github.com/brain-life/app-dipy-MAPMRI/blob/63f6273e871f189f5be925695f7daf153d761b47/submit.pbs#L21

**Comment by aarya22** [comment]
Great to hear. I don't know if the png is correct or not, maybe Elef or Ariel can help? I am meeting Ariel later today I can ask him about it.

As for the submit.pbs, I think the issue is that the pbs script is looking for 4 track1.tck files as output, but the application seems to be producing a png file called MAPMRI_maps_regularization.png. I can edit the pbs script to make it look for this file instead.

**Comment by Garyfallidis** [comment]
Have in mind that cvxopt is not used anymore. We use cvxpy. See later
updates in master.

Are you planning to use Mapmri or Mapl ? I think Mapl maybe better for
clinical datasets. It's the same API - same classname for both.

As we discuss before it would be much easier if first you submit a workflow
on that in DIPY to make sure that all is good
and have multiple reviewers looking the code that are part of the
development team.

Here is an example of a workflow using the ConstantSolidAngle algorithm.
https://github.com/Garyfallidis/dipy/blob/det_track_workflow/bin/dipy_csa

We should have something similar for mapmri.

**Comment by Garyfallidis** [comment]
I can arrange a meeting with you to help with that.

**Comment by aarya22** [comment]
@soichih I have a pull-request to fix the pbs file, check it out.

@Garyfallidis I can't find the workflow for mapmri in the dipy workflows folder. I am pretty sure I can make the workflow myself, but I am not sure what you mean by "submit" a workflow. Do you want me to submit a pull-request with a new workflow with mapmri?

**Comment by aarya22** [comment]
@Garyfallidis I've created a workflow and a pull-request for the app. Not sure how to exactly create a workflow but check it [out](https://github.com/nipy/dipy/pull/1350): 

@soichih and @francopestilli Hopefully by creating workflows like this for our applications we can get more feedback from the dipy community and updates for our applications, as well make the applications far easier to make.

**Comment by francopestilli** [comment]
@aarya22 this is great thanks! I hope @Garyfallidis can let us know if this is a good way forward!
